services:
  backend:
    build: .
    image: backend:1.0
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - transcendence-net

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
  #     - prometheus-data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   ports:
  #     - "9090:9090"

networks:
  transcendence-net:
    driver: bridge
    name: transcendence-net