global:
  resolve_timeout: 5m

route:
  receiver: 'discord-notifications'
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'discord-notifications'
    discord_configs:
    - webhook_url: 'https://discord.com/api/webhooks/1448680552025555028/9xOCgoM8m_sTnJEiXaDKY8vPKeH0nnsCxxhL0-vJlta36YnYGz3joo_h21B7PsLTqP2I'
      send_resolved: true
      title: '{{ .Status | toUpper }} - {{ .CommonLabels.alertname }}'
      message: >-
        {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Severity:** {{ .Labels.severity }}
          **Description:** {{ .Annotations.description }}
        {{ end }}